# Generated by Django 5.2.8 on 2025-11-27 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplies', '0002_remove_inventoryhistoryitem_history_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='supplies.supply')),
            ],
            options={
                'verbose_name': '5. Histórico de inventario',
                'verbose_name_plural': '5. Históricos de inventarios',
            },
        ),
        migrations.CreateModel(
            name='InventoryHistoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=10)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='datalogs.inventoryhistory')),
            ],
            options={
                'verbose_name': 'Insumo histórico',
                'verbose_name_plural': 'Insumos históricos',
            },
        ),
    ]
