# Generated by Django 5.2.8 on 2025-11-27 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datalogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryhistory',
            options={'verbose_name': 'Registro de inventario', 'verbose_name_plural': 'Históricos de inventarios'},
        ),
        migrations.AlterModelOptions(
            name='inventoryhistoryitem',
            options={'verbose_name': 'Insumo registro', 'verbose_name_plural': 'Insumos registro'},
        ),
    ]
