# Generated by Django 5.2.5 on 2025-12-04 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalogs', '0002_alter_inventoryhistory_options_and_more'),
        ('supplies', '0006_remove_items_base_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryhistory',
            name='supply',
        ),
        migrations.AddField(
            model_name='inventoryhistory',
            name='cabin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_histories', to='supplies.cabin'),
        ),
        migrations.AddField(
            model_name='inventoryhistoryitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='supplies.items'),
        ),
        migrations.AlterField(
            model_name='inventoryhistoryitem',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
