# Generated by Django 5.2.5 on 2025-11-26 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cabin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre de la cabaña')),
            ],
            options={
                'verbose_name': '1. Cabaña',
                'verbose_name_plural': '1. Cabañas',
            },
        ),
        migrations.CreateModel(
            name='categoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre de la categoría')),
            ],
            options={
                'verbose_name': '3. Categoria de insumo',
                'verbose_name_plural': '3. Categoria de insumos',
            },
        ),
        migrations.CreateModel(
            name='InventoryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '5. Histórico de inventario',
                'verbose_name_plural': '5. Históricos de inventarios',
            },
        ),
        migrations.CreateModel(
            name='InventoryHistoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=10)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='supplies.inventoryhistory')),
            ],
            options={
                'verbose_name': 'Insumo histórico',
                'verbose_name_plural': 'Insumos históricos',
            },
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre del insumo')),
                ('base_quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad Bbse')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies.categoryitem', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': '2. Insumo',
                'verbose_name_plural': '2. Insumos',
            },
        ),
        migrations.CreateModel(
            name='supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cabin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplies.cabin', verbose_name='Cabaña')),
            ],
            options={
                'verbose_name': '4. Inventario de cabaña',
                'verbose_name_plural': '4. Inventarios de cabañas',
            },
        ),
        migrations.AddField(
            model_name='inventoryhistory',
            name='supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='supplies.supply'),
        ),
        migrations.CreateModel(
            name='SupplyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('status', models.CharField(choices=[('disponible', 'Disponible'), ('bajo', 'Bajo stock'), ('pendiente', 'Pendiente'), ('agotado', 'Agotado')], default='disponible', max_length=10, verbose_name='Estado')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies.items', verbose_name='Insumo')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='supplies.supply')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Inventario',
            },
        ),
    ]
