# Generated by Django 5.2.5 on 2025-11-18 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cabin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre de la cabaña')),
            ],
            options={
                'verbose_name': 'Cabaña',
                'verbose_name_plural': 'Cabañas',
            },
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre del insumo')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
            },
        ),
        migrations.CreateModel(
            name='supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('status', models.CharField(choices=[('disponible', 'Disponible'), ('pendiente', 'Pendiente'), ('agotado', 'Agorado')], default='disponible', max_length=10, verbose_name='Estado')),
                ('cabin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies.cabin', verbose_name='Cabaña')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies.items', verbose_name='Insumo')),
            ],
            options={
                'verbose_name': 'Insumo de cabaña',
                'verbose_name_plural': 'Insumos de cabañas',
                'unique_together': {('cabin', 'item')},
            },
        ),
    ]
