# Generated by Django 5.2.5 on 2025-11-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='status',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('pendiente', 'Pendiente'), ('Agotado', 'agotado')], default='disponible', max_length=10, verbose_name='Estado'),
        ),
    ]
