# Generated by Django 5.2.8 on 2025-11-27 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryhistoryitem',
            name='history',
        ),
        migrations.DeleteModel(
            name='InventoryHistory',
        ),
        migrations.DeleteModel(
            name='InventoryHistoryItem',
        ),
    ]
