# Generated by Django 5.2.5 on 2025-11-18 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0002_alter_supply_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre de la categoría')),
            ],
            options={
                'verbose_name': 'Categoria de insumo',
                'verbose_name_plural': 'Categoria de insumos',
            },
        ),
        migrations.AddField(
            model_name='items',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies.categoryitem', verbose_name='Categoría'),
        ),
    ]
