# Generated by Django 5.2.8 on 2025-11-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0002_remove_inventoryhistoryitem_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabin',
            name='status',
            field=models.CharField(choices=[('lista', 'Lista'), ('abasteciendo', 'En Abastecimiento'), ('disponible', 'Disponible')], default='disponible', max_length=50, verbose_name='Estado'),
        ),
    ]
