# Generated by Django 5.2.5 on 2025-11-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0003_categoryitem_items_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='status',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('pendiente', 'Pendiente'), ('agotado', 'Agotado')], default='disponible', max_length=10, verbose_name='Estado'),
        ),
    ]
