# Generated by Django 5.2.5 on 2025-12-03 22:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0003_cabin_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cabin',
            options={'verbose_name': 'Cabaña', 'verbose_name_plural': 'Cabañas'},
        ),
        migrations.AlterModelOptions(
            name='categoryitem',
            options={'verbose_name': 'Categoria de insumo', 'verbose_name_plural': 'Categoria de insumos'},
        ),
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name': 'Insumo', 'verbose_name_plural': 'Insumos'},
        ),
        migrations.AlterModelOptions(
            name='supply',
            options={'verbose_name': 'Inventario de cabaña', 'verbose_name_plural': 'Inventarios de cabañas'},
        ),
        migrations.AddField(
            model_name='supply',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=150, verbose_name='Nombre del inventario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cabin',
            name='status',
            field=models.CharField(choices=[('lista', 'Lista'), ('abasteciendo', 'En Abastecimiento'), ('preparacion', 'En Preparacion'), ('disponible', 'Disponible')], default='disponible', max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='items',
            name='base_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad Base'),
        ),
        migrations.CreateModel(
            name='BaseSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=100, verbose_name='Nombre del inventario base')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cabin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplies.cabin', verbose_name='Cabaña')),
            ],
            options={
                'verbose_name': 'Inventario base',
                'verbose_name_plural': 'Inventarios base',
            },
        ),
    ]
