# Generated by Django 5.2.5 on 2025-12-03 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0004_alter_cabin_options_alter_categoryitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSupplyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('base_supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='supplies.basesupply')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies.items', verbose_name='Insumo')),
            ],
        ),
    ]
