# Generated by Django 5.2.5 on 2025-11-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0004_alter_supply_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='base_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad Bbse'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='status',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('bajo', 'Bajo Stock'), ('agotado', 'Agotado'), ('pendiente', 'Pendiente')], default='disponible', max_length=10, verbose_name='Estado'),
        ),
    ]
