# Generated by Django 5.2.5 on 2025-11-19 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0005_items_base_quantity_alter_supply_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabin_name', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Histórico de inventario',
                'verbose_name_plural': 'Históricos de inventarios',
            },
        ),
        migrations.AlterField(
            model_name='supply',
            name='cabin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplies.cabin', verbose_name='Cabaña'),
        ),
    ]
