# Generated by Django 5.2.5 on 2025-12-03 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0005_basesupplyitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='base_quantity',
        ),
    ]
