# Generated by Django 5.2.5 on 2025-11-19 18:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0006_inventoryhistory_alter_supply_cabin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supply',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='supply',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='supply',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SupplyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('status', models.CharField(choices=[('disponible', 'Disponible'), ('bajo', 'Bajo stock'), ('pendiente', 'Pendiente'), ('agotado', 'Agotado')], default='disponible', max_length=10, verbose_name='Estado')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies.items', verbose_name='Insumo')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='supplies.supply')),
            ],
        ),
        migrations.RemoveField(
            model_name='supply',
            name='item',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='status',
        ),
    ]
