# Generated by Django 5.2.5 on 2025-11-19 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0007_alter_supply_options_alter_supply_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supply',
            options={'verbose_name': 'Inventario', 'verbose_name_plural': 'Inventarios'},
        ),
        migrations.AlterModelOptions(
            name='supplyitem',
            options={'verbose_name': 'Insumo', 'verbose_name_plural': 'Inventario'},
        ),
        migrations.RemoveField(
            model_name='inventoryhistory',
            name='cabin_name',
        ),
        migrations.RemoveField(
            model_name='inventoryhistory',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='inventoryhistory',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='inventoryhistory',
            name='status',
        ),
        migrations.AddField(
            model_name='inventoryhistory',
            name='supply',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='supplies.supply'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='InventoryHistoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=10)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='supplies.inventoryhistory')),
            ],
            options={
                'verbose_name': 'Insumo histórico',
                'verbose_name_plural': 'Insumos históricos',
            },
        ),
    ]
