# Generated by Django 5.2.5 on 2025-11-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('without_role', 'Sin rol asignado'), ('admin', 'Administrador'), ('manager', 'Encargado de preparación de cabañas')], default='Sin rol asignado', max_length=20, verbose_name='Rol'),
        ),
    ]
